services:

  qiscusDb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: qiscus
    ports:
      - 3307:3306
    volumes:
      # dipakai kalau ingin persistance
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  agentAllocation:
    # ada Dockerfile yang satu folder dengan docker-compose.yaml
    build: .
    restart: always
    environment:
      CONNECTION_STRING: root:12345@tcp(172.17.0.1:3307)/qiscus?charset=utf8&parseTime=True&loc=Local
    ports:
      - 8080:8080