name: Deploy to EC2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d "/home/ubuntu/agent-allocation" ]
          then
            git clone git@github.com:AnggunPermata/agent-allocation.git /home/ubuntu/agent-allocation
          fi
          cd /home/ubuntu/agent-allocation
          git pull origin main
          docker stop agentAllocation
          docker rm agentAllocation
          docker stop qiscusDB
          docker rm qiscusDB
          docker build -t anggunpermatata/agent-allocation:latest .
          docker run --name qiscusDB -e MYSQL_ROOT_PASSWORD=12345 -e MYSQL_DATABASE=qiscus -p 3307:3306 -d mysql:latest
          docker run -d --name agentAllocation -p 8080:8080 -e "CONNECTION_STRING=root:12345@tcp(18.219.131.123:3307)/qiscus?charset=utf8&parseTime=True&loc=Local" -e "HTTP_PORT=8080" anggunpermatata/agent-allocation:latest